In [40]:
import numpy as np
import sympy as sp

In [26]:
A = np.array([[89,75,22,102],[75,116,27,120],[22,27,33,62],[102,120,62,200]])

In [6]:
#Aufgabe A
ew,ev = np.linalg.eig(A)
print("ew\n", ew)
print("ev\n", ev)

ew
 [361.75382302  42.74593101  26.33718907   7.16305691]
ev
 [[-0.42552429 -0.42476765  0.76464379 -0.23199439]
 [-0.50507589 -0.54267519 -0.64193252 -0.19576676]
 [-0.20612674  0.54869183 -0.05515612 -0.80833585]
 [-0.72203822  0.4733005   0.01415338  0.50442752]]


In [38]:
#Aufgabe b
print(np.round(ev@ev.T))

[[ 1.  0. -0.  0.]
 [ 0.  1. -0. -0.]
 [-0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


In [49]:
#Augabe c
V=ev
V_inv = np.linalg.inv(V)
A_diag = np.round(V_inv.dot(A).dot(V))
sp.Matrix(A_diag)

Matrix([
[362.0,    0,    0,   0],
[    0, 43.0,    0,   0],
[    0,    0, 26.0,   0],
[    0,    0,    0, 7.0]])

In [43]:
#Aufgabe d 1
res = np.eye( A.shape[0] )
for i in range(20):
    res = res.dot(A)
sp.Matrix(res)

Matrix([
[2.66754227097944e+50, 3.16623820859875e+50, 1.29217483659217e+50, 4.52633961205365e+50],
[3.16623820859875e+50, 3.75816514799211e+50, 1.53374639431891e+50, 5.37253695309439e+50],
[1.29217483659217e+50, 1.53374639431891e+50, 6.25937900398833e+49, 2.19258836577634e+50],
[4.52633961205365e+50, 5.37253695309438e+50, 2.19258836577634e+50, 7.68038448969867e+50]])

In [42]:
#Aufgabe d 2
res = V @ D**20 @ np.linalg.inv(V)
sp.Matrix(res)

Matrix([
[ 2.6675422709794e+50, 3.16623820859871e+50, 1.29217483659216e+50,  4.5263396120536e+50],
[3.16623820859871e+50, 3.75816514799206e+50, 1.53374639431889e+50, 5.37253695309431e+50],
[1.29217483659215e+50, 1.53374639431889e+50, 6.25937900398826e+49, 2.19258836577631e+50],
[ 4.5263396120536e+50, 5.37253695309432e+50, 2.19258836577631e+50, 7.68038448969858e+50]])

In [41]:
#Aufgabe d 3
A_3 = np.linalg.matrix_power(A, 20)
sp.Matrix(res)

Matrix([
[2.66754227097944e+50, 3.16623820859875e+50, 1.29217483659217e+50, 4.52633961205365e+50],
[3.16623820859875e+50, 3.75816514799211e+50, 1.53374639431891e+50, 5.37253695309439e+50],
[1.29217483659217e+50, 1.53374639431891e+50, 6.25937900398833e+49, 2.19258836577634e+50],
[4.52633961205365e+50, 5.37253695309438e+50, 2.19258836577634e+50, 7.68038448969867e+50]])