In [1]:
import numpy as np
import matplotlib.pyplot as plt

Anlegen einer Matrix

In [73]:
A = np.array([[2,4],[-1,3],[0,-2]])
print(A)

[[ 2  4]
 [-1  3]
 [ 0 -2]]


Singulärwert anzeigen

In [74]:
U, sigma, VT= np.linalg.svd(A)
print(sigma) #Singulärwerte

[5.47722558 2.        ]


Sigma wird zu der Diagonal Matrix

In [81]:
sigma = np.diag(sigma)
sigma

array([5.47722558, 2.        ])

Pseudo inverse

1. Sigma als Diagonalmatrix für Berechnung erstellen

In [84]:
# Diagonalmatrix S erstellen
S = np.zeros(A.shape)
S[0,0] = sigma[0] #erster Singulärwert
S[1,1] = sigma[1]#zweiter Singulärwert
#ersetze weiter, falls mehr als 2 Singulärwert
S

array([[5.47722558, 0.        ],
       [0.        , 2.        ],
       [0.        , 0.        ]])

2. Prüfen ob Ursprüngliche A heraus kommt. (Werte runden)

In [80]:
U@S@VT

array([[ 2.00000000e+00,  4.00000000e+00],
       [-1.00000000e+00,  3.00000000e+00],
       [-5.55111512e-17, -2.00000000e+00]])

3. wobei Σ + aus dem transponierten Σ besteht, in dem von allen von Null verschiedenen Werten der Kehrwert berechnet wurde. (Σ + berechnen)

In [85]:
S_P = np.zeros(A.T.shape) #Weil A plus eine nxm ist und A eine mxn
S_P[0,0] = 1/sigma[0] #Kehrwert der von Null verschiedenen Werten
S_P[1,1] = 1/sigma[1]
S_P

array([[0.18257419, 0.        , 0.        ],
       [0.        , 0.5       , 0.        ]])

4. A+ berechnen.

In [88]:
A_P = VT.T@S_P@U.T #VT und U müssen Transponiert werden da in der Formel U und V die Rollen tauschen
A_P

array([[ 0.31666667, -0.36666667,  0.08333333],
       [ 0.08333333,  0.16666667, -0.08333333]])

Matrix * Matrix

In [93]:
APA = A_P@A
AAP = A@A_P
print("APA \n", APA)
print("AAP \n", AAP)

APA 
 [[ 1.00000000e+00 -6.10622664e-16]
 [-5.55111512e-17  1.00000000e+00]]
AAP 
 [[ 0.96666667 -0.06666667 -0.16666667]
 [-0.06666667  0.86666667 -0.33333333]
 [-0.16666667 -0.33333333  0.16666667]]


singuläres Gleichungssystem:

    3x+4y = 1
    3x-y  = 2
    2x    = 3
    
Berechne mit Hilfe der Pseudoinversen A+ die Näherungslösung des Systems

In [98]:
y = np.array([[1],[2],[3]])
lsg = A_P@y
lsg

array([[-0.16666667],
       [ 0.16666667]])

Vergleichen Sie die Lösung der letzten Teilaufgabe mit der Näherungslösung welche Sie mit
der Normalengleichung erhalten

In [99]:
lsg2 = np.linalg.inv(A.T@A)@A.T@y
lsg2

array([[-0.16666667],
       [ 0.16666667]])

Sie haben gesehen, dass sich die quadratische Form als q(x) = x T Ax mit A ∈ R 4×4 und
A T = A darstellen lässt. Bestimmen Sie A.

In [103]:
A = np.array([[3,0,0,-1],[0,3,-1,0],[0,-1,3,0],[-1,0,0,3]])
print(A)

[[ 3  0  0 -1]
 [ 0  3 -1  0]
 [ 0 -1  3  0]
 [-1  0  0  3]]


Wie lautet die Basis B, in der die Mischterme verschwinden? Geben Sie die quadratische Form in dieser Basis an (der Vektor x werde dabei in den Vektor y transformiert).

In [107]:
lamb, V = np.linalg.eig(A)

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [-0.70710678,  0.70710678,  0.        ,  0.        ]])

In [108]:
lamb#sind die Eigenwerte und können direkt in die quadratische Form mit dem jeweiligen yn^2 geschrieben werden

array([4., 2., 4., 2.])

In [109]:
V #ist in diesemfall die Basis B

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [-0.70710678,  0.70710678,  0.        ,  0.        ]])