In [1]:
import numpy as np

Erstellen der Matrizen

In [28]:
A = np.array([[-7,4,4],[4,-1,8],[4,8,-1]])
A = 1/9*A
print(A)
B = np.array([[1,0,-1],[0,4,-3],[-1,-3,20]])

[[-0.77777778  0.44444444  0.44444444]
 [ 0.44444444 -0.11111111  0.88888889]
 [ 0.44444444  0.88888889 -0.11111111]]


In [18]:
def kappa(A):
    eig_max = max(abs((np.linalg.eigvals(A))))
    eig_min = min(abs((np.linalg.eigvals(A))))
    return eig_max/eig_min
print(" kappa A= \n",kappa(A))
print(" kappa B= \n",kappa(B))


 kappa A= 
 1.0000000000000002
 kappa B= 
 21.95516850022577


In [27]:
print( A @ A.T)
print(B @ B.T)

[[1.00000000e+00 3.35808199e-17 3.74357609e-17]
 [3.35808199e-17 1.00000000e+00 5.48258284e-18]
 [3.74357609e-17 5.48258284e-18 1.00000000e+00]]
[[  2   3 -21]
 [  3  25 -72]
 [-21 -72 410]]


In [29]:
A = np.array([[-19,9,0,0],[-12,5,0,0],[0,0,6,-2]])

In [36]:
U, S, VT= np.linalg.svd(A)
sigma1 = S[0]
u1 = U[:, 0]
v1 = VT[0, :]

A_approx = np.outer(u1, sigma1 * v1)

print(A_approx)

[[-19.1150923    8.74852916   0.           0.        ]
 [-11.81377674   5.40688837   0.           0.        ]
 [ -0.           0.           0.           0.        ]]
