# Lösungen zu den Python-Aufgaben aus Kapitel 1

In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from IPython.display import display

## Aufgabe 4

### a)

In [2]:
M1 = np.array([[7,8],[0,9]])
ew, ev = np.linalg.eig( M1 )

Eigenwerte:

In [3]:
list( ew )

[7.0, 9.0]

Eigenvektoren (normalisiert):

In [4]:
for k in range( M1.shape[0] ):
    display( sp.Matrix( np.round( ev[:,k], 4 ) ) ) 

Matrix([
[1.0],
[  0]])

Matrix([
[0.9701],
[0.2425]])

### d)

In [5]:
M2 = np.array([[0,-1],[1,2]])
ew, ev = np.linalg.eig( M2 )

Eigenwerte:

In [6]:
ew

array([1., 1.])

Algebraische Vielfachheit 1.

Eigenvektoren (normalisiert):

In [7]:
for k in range( M2.shape[0] ):
    display( sp.Matrix( np.round( ev[:,k], 4 ) ) ) 

Matrix([
[-0.7071],
[ 0.7071]])

Matrix([
[-0.7071],
[ 0.7071]])

Zweimal der gleiche Vektor, geometrische Vielfachheit 1.

### l)

In [8]:
M3 = np.array([[1,0,0],[-5,0,2],[0,0,1]])
ew, ev = np.linalg.eig( M3 )

Eigenwerte:

In [9]:
ew

array([0., 1., 1.])

Algebraische Vielfachheit 1 für Eigenwert 0 und 2 für Eigenwert 1.

Eigenvektoren (normalisiert):

In [10]:
for k in range( M3.shape[0] ):
    display( sp.Matrix( np.round( ev[:,k], 4 ) ) ) 

Matrix([
[  0],
[1.0],
[  0]])

Matrix([
[ 0.1961],
[-0.9806],
[      0]])

Matrix([
[     0],
[0.8944],
[0.4472]])

Geometrische Vielfachheit 1 für Eigenwert 0 und 2 für Eigenwert 1.

### m)

In [11]:
M4 = np.array([[1,1,0],[0,-1,-1],[2,2,0]])
ew, ev = np.linalg.eig( M4 )

Eigenwerte:

In [12]:
ew

array([ 1.10346248e-15+0.j, -2.08166817e-16+1.j, -2.08166817e-16-1.j])

Numerische Artefakte bereinigt:

In [13]:
np.round( ew, 10 )

array([ 0.+0.j, -0.+1.j, -0.-1.j])

Die Eigenwerte sind komplex!

Eigenvektoren (normalisiert):

In [14]:
for k in range( M4.shape[0] ):
    display( sp.Matrix( np.round( ev[:,k], 4 ) ) ) 

Matrix([
[ 0.5774],
[-0.5774],
[ 0.5774]])

Matrix([
[         -0.378],
[0.378 - 0.378*I],
[        -0.7559]])

Matrix([
[         -0.378],
[0.378 + 0.378*I],
[        -0.7559]])

im Allgemeinen ebenfalls komplex!

## Aufgabe 16

In [15]:
A = np.array([[89,75,22,102],[75,116,27,120],[22,27,33,62],[102,120,62,200]], dtype=float)
A

array([[ 89.,  75.,  22., 102.],
       [ 75., 116.,  27., 120.],
       [ 22.,  27.,  33.,  62.],
       [102., 120.,  62., 200.]])

### a)

Berechung der Eigenwerte und Eigenvektoren:

In [16]:
ew, ev = np.linalg.eig(A)

Eigenwerte:

In [17]:
ew

array([361.75382302,  42.74593101,  26.33718907,   7.16305691])

Eigenvektoren (Spaltenvektoren):

In [18]:
ev

array([[-0.42552429, -0.42476765,  0.76464379, -0.23199439],
       [-0.50507589, -0.54267519, -0.64193252, -0.19576676],
       [-0.20612674,  0.54869183, -0.05515612, -0.80833585],
       [-0.72203822,  0.4733005 ,  0.01415338,  0.50442752]])

### b)

In [19]:
S = np.zeros([ev.shape[1], ev.shape[1]])

for i in range(ev.shape[1]):
    for j in range(ev.shape[1]):
        S[i,j] = np.vdot( ev[:,i], ev[:,j])

np.round( S, 10 )

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0.,  0.],
       [-0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])

Die Skalarprodukte der Eigenvektoren $\mathbf{v}_i$ und $\mathbf{v}_j$ sind gleich null für alle $i\neq j$ und damit stehen alle Eigenvektoren orthogonal zueinander. Die Eigenvektoren stehen orthogonal zueinander, weil die Matrix $A$ symmetrisch ist (Beweis siehe Skript).

Obiger Code ohne `for`-Loops (überlegen Sie sich, warum das das gleiche ist - Hinweis: Definition des Matrizenprodukts):

In [20]:
np.round( np.dot( ev.T, ev ), 10 )

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0.,  0.],
       [-0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])

### c)

In [21]:
V = ev
Vinv = np.linalg.inv(V)
D = np.round( Vinv.dot(A).dot(V), 10 )
D

array([[361.75382302,   0.        ,  -0.        ,  -0.        ],
       [ -0.        ,  42.74593101,  -0.        ,   0.        ],
       [ -0.        ,   0.        ,  26.33718907,   0.        ],
       [  0.        ,   0.        ,  -0.        ,   7.16305691]])

### d)

Matrix $A$ 20x mit sich selbst multiplizieren:

In [22]:
%%timeit
res = np.eye( A.shape[0] )
for i in range(20):
    res = res.dot(A)

14.8 µs ± 53.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


(Code noch einmal wiederholen, %%timeit speichert keine Variablen ausserhalb seines Scope)

In [23]:
res = np.eye( A.shape[0] )
for i in range(20):
    res = res.dot(A)
sp.Matrix(res) # Sympy kann Latex-Ausgabe

Matrix([
[2.66754227097944e+50, 3.16623820859875e+50, 1.29217483659217e+50, 4.52633961205365e+50],
[3.16623820859875e+50, 3.75816514799211e+50, 1.53374639431891e+50, 5.37253695309438e+50],
[1.29217483659217e+50, 1.53374639431891e+50, 6.25937900398834e+49, 2.19258836577634e+50],
[4.52633961205366e+50, 5.37253695309438e+50, 2.19258836577634e+50, 7.68038448969867e+50]])

Mit `np.linalg.matrix_power()`:

In [24]:
%%timeit
res = np.linalg.matrix_power(A, 20)

8.77 µs ± 8.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
res = np.linalg.matrix_power(A, 20)
sp.Matrix(res)

Matrix([
[2.66754227097944e+50, 3.16623820859875e+50, 1.29217483659217e+50, 4.52633961205365e+50],
[3.16623820859875e+50, 3.75816514799211e+50, 1.53374639431891e+50, 5.37253695309438e+50],
[1.29217483659217e+50, 1.53374639431891e+50, 6.25937900398834e+49, 2.19258836577634e+50],
[4.52633961205365e+50, 5.37253695309438e+50, 2.19258836577634e+50, 7.68038448969867e+50]])

Mit berechneter Diagonalmatrix:

In [26]:
%%timeit
res = Vinv @ D ** 20 @ V

4.69 µs ± 2.89 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
res = Vinv @ D ** 20 @ V
sp.Matrix(res)

Matrix([
[ 2.66754227098428e+50,  2.66279899310823e+50, -4.79342694656279e+50,  1.45433493939433e+50],
[ 2.66279899310822e+50,  2.65806414946966e+50, -4.78490353674341e+50,  1.45174892048942e+50],
[-4.79342694656279e+50, -4.78490353674342e+50,  8.61352494465107e+50, -2.61336000694312e+50],
[ 1.45433493939433e+50,  1.45174892048943e+50, -2.61336000694313e+50,  7.92898443990797e+49]])

Sind $V, V^{-1}$ und die Diagonalmatrix $D$ schon berechnet, ist der letzte Ansatz der schnellste.